<?php

/*
|--------------------------------------------------------------------------
| Carrier delivery zones (Atlas Colis)
|--------------------------------------------------------------------------
|
| GENERATED FILE — do not edit by hand. Refresh it with:
|
|     php artisan shipping:import-atlas           (writes the file)
|     php artisan shipping:import-atlas --dry-run (reports the diff)
|
| Mirrored from https://atlascolis.ma/tarifs.php on 2026-09-28: 447 rows, one per delivery
| city, with the fee the carrier actually charges for it.
|
| This is the single source of truth for:
|
|   - the city <select> on the checkout page;
|   - the shipping cost of every order (see ShippingService);
|   - the "deliverable" check, so an order is never taken for a city
|     the carrier does not serve.
|
| `code` is the carrier's own zone id and is not unique (it reuses a
| few), so lookups go through ShippingZoneService, which indexes the
| rows by city name.
|
*/

return [
    'source' => 'https://atlascolis.ma/tarifs.php',
    'fetched_at' => '2026-09-28',

    // code  | city | fee | delay | refusal | return
    'zones' => [

        ['code' => 'BML', 'city' => 'Beni Mellal', 'fee' => 20, 'delay' => '8h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OMS', 'city' => 'OULAD MOUSSA', 'fee' => 25, 'delay' => '8h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'AOR', 'city' => 'AFOURAR', 'fee' => 25, 'delay' => '8h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'EAT', 'city' => 'EL AYAYTA', 'fee' => 25, 'delay' => '12h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'SISSA', 'city' => 'SIDI ISSA', 'fee' => 25, 'delay' => '12h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'SOS', 'city' => 'SOUK SEBT OULAD NEMA', 'fee' => 25, 'delay' => '12h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'BAYAT', 'city' => 'BENI AYAT', 'fee' => 25, 'delay' => '8h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'TIML', 'city' => 'TIMOULIT', 'fee' => 25, 'delay' => '8h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'KRZ', 'city' => 'EL KRAZA', 'fee' => 25, 'delay' => '8h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OAD', 'city' => 'OULAD AYAD SOUK SEBT', 'fee' => 25, 'delay' => '8h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'DZH', 'city' => 'DAR OULED ZIDOH', 'fee' => 30, 'delay' => '12h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OZ', 'city' => 'OULAD ZEMAM', 'fee' => 25, 'delay' => '12h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'FBS', 'city' => 'FKIH BEN SALAH', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'BRADIA', 'city' => 'HED EL BRADIA', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'SIJBR', 'city' => 'SIDI JABER', 'fee' => 25, 'delay' => '12h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ODRIS', 'city' => 'OULAD DRISS', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OUAICH', 'city' => 'OULAD I3ICH', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ZWR', 'city' => 'EZZWAYR', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OLYSF', 'city' => 'OULAD YOUSSEF', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OUSAID', 'city' => 'OULAD SAID EL OUED', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'BZZ', 'city' => 'BEZZAZA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ARBAA', 'city' => 'AIT RBAA TADLA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'KAT', 'city' => 'KASBA TADLA', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'AITALI', 'city' => 'AIT ALI TADLA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'KSB', 'city' => 'EL KSIBA', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'IGHRM', 'city' => 'IGHRAM LAALAM', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ZWCH', 'city' => 'ZAWIT CHIKH', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'TNGH', 'city' => 'TANOUGHA', 'fee' => 25, 'delay' => '12h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'FRT', 'city' => 'FERYATA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'FZW', 'city' => 'FOM ZAWIA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'TGZR', 'city' => 'TAGZIRT', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'FSNR', 'city' => 'FOM ANSER', 'fee' => 25, 'delay' => '12h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ADZ', 'city' => 'ADOUZ', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'AZL', 'city' => 'AZILAL', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OUZG', 'city' => 'OUAWIZGHT', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'KHRG', 'city' => 'KHOURIBGA', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'BJNB', 'city' => 'BOUJNIBA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'HTN', 'city' => 'HATTAN', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'BLNR', 'city' => 'BOULANOUAR', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OZEM', 'city' => 'OUED ZEM', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'TCHRFT', 'city' => 'TACHRAFT', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'GFF', 'city' => 'EL GUEFAF', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'BJD', 'city' => 'BEJAAD', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'KHNF', 'city' => 'KHENIFRA', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'MRT', 'city' => 'MRIRT', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'GLMS', 'city' => 'AGELMOUS', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'BRJ', 'city' => 'EL BORJ-reg khenifra', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'TGHSL', 'city' => 'TIGHSALIN', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ISHK', 'city' => 'AIT ISHAK', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OUMN', 'city' => 'OUAWMANA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'MYBZ', 'city' => 'MOLAY BOUAZA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'HRI', 'city' => 'EL HRI', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'KFNS', 'city' => 'KAFNSOUR', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'KBAB', 'city' => 'EL KBAB', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'FMD', 'city' => 'FOUM OUDI', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OMRAH', 'city' => 'OULAD MERAH', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ZONEIND', 'city' => 'ZONE industriel BENI MELLAL', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'GHILA', 'city' => 'MGHILA', 'fee' => 20, 'delay' => '8h', 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'CSA', 'city' => 'CASABLANCA', 'fee' => 35, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'RBT', 'city' => 'RABAT', 'fee' => 35, 'delay' => '24h', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'FES', 'city' => 'FES', 'fee' => 35, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KECH', 'city' => 'MARRAKECH', 'fee' => 35, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AGA', 'city' => 'AGADIR', 'fee' => 35, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OUJD', 'city' => 'OUJDA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TNG', 'city' => 'TANGER', 'fee' => 35, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'hel', 'city' => 'hel MARBAA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'RGAA', 'city' => 'OULAD RGIAA', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'OULADALI', 'city' => 'OULAD ALI', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'BMLL', 'city' => 'BENI MELLAL', 'fee' => 25, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ODAM', 'city' => 'oued amlil', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Guez', 'city' => 'Gueznaia', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Ouazza', 'city' => 'Ouazzane', 'fee' => 40, 'delay' => '48h', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Asil', 'city' => 'Asilah', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Chefc', 'city' => 'Chefchaouen', 'fee' => 45, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'FniQ', 'city' => 'Fnideq', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MDQ', 'city' => 'Madiq', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MRTL', 'city' => 'Martil', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'LRCH', 'city' => 'Larache', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KSGH', 'city' => 'Ksar Sghir', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TTO', 'city' => 'Tetouan', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KSKB', 'city' => 'Ksar El Kebir', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'CNEGR', 'city' => 'Cabo Negro', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'MRSGHIR', 'city' => 'marina smir', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SGHR', 'city' => 'Kabila', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SKSAH', 'city' => 'Souk Khemis du Sahel', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'AlHoceima', 'city' => 'Al Hoceima', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Bouzaghlal', 'city' => 'Bouzaghlal', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Azla', 'city' => 'Azla', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'bouan', 'city' => 'bouanane tetoun', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'laouamra', 'city' => 'laouamra', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'belyonnech', 'city' => 'belyonnech', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Aindorij', 'city' => 'Ain dorij', 'fee' => 45, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'zoumiouazzane', 'city' => 'zoumi ouazzane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'JorfElMelha', 'city' => 'Jorf El Melha', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AjdirHociema', 'city' => 'Ajdir Hociema', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AinDfaliouazzane', 'city' => 'Ain Dfali ouazzane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Imzouren', 'city' => 'Imzouren', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BabBerred', 'city' => 'Bab Berred', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Dlalha', 'city' => 'Dlalha', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BabTaza', 'city' => 'Bab Taza', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'ElJebeha', 'city' => 'El Jebeha', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BenRezin', 'city' => 'Ben Rezin', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Alanssar', 'city' => 'Alanssar', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Khemismadiaq', 'city' => 'Khemis madiaq', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'AKCHOUR', 'city' => 'AKCHOUR', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'CHRAFATChefchaouen', 'city' => 'CHRAFAT Chefchaouen', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'ELJADIDA', 'city' => 'EL JADIDA', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SAFI', 'city' => 'SAFI', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ESSAOUIRA', 'city' => 'ESSAOUIRA', 'fee' => 40, 'delay' => '48h', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SIDIBOUZID', 'city' => 'SIDIBOUZID', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'GHADBAN', 'city' => 'GHADBAN', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'JORSFLASFRE', 'city' => 'JORSF LASFRE', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'HAWZIA', 'city' => 'HAWZIA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'AZAMMOUR', 'city' => 'AZAMMOUR', 'fee' => 45, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TNINCHTOUKA', 'city' => 'TNIN CHTOUKA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BIRJDID', 'city' => 'BIR JDID', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HEDSWALAM', 'city' => 'HED SWALAM', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SIDIREHAL', 'city' => 'SIDI REHAL', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TAMARIS', 'city' => 'TAMARIS', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'DARBOUAZA', 'city' => 'DAR BOUAZA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SIDIBANOUR', 'city' => 'SIDIBANOUR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KHEMISZMAMRA', 'city' => 'KHEMIS ZMAMRA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SIDISMAIL', 'city' => 'SIDI SMAIL', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'OUALIDIA', 'city' => 'OUALIDIA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HEDOULEDFREJ', 'city' => 'HED OULED FREJ', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TNINGHARBIA', 'city' => 'TNIN GHARBIA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SIDIABED', 'city' => 'SIDI ABED', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OULEDGHANAM', 'city' => 'OULED GHANAM', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'LARBAAWNAT', 'city' => 'LARBA AWNAT', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'HEDAWNAT', 'city' => 'HED AWNAT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'YOUSSOUFIA', 'city' => 'YOUSSOUFIA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'JAMAATSHIM', 'city' => 'JAMAAT SHIM', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MKNS', 'city' => 'MEKNES', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OURZZ', 'city' => 'OUARZAZAT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KNT', 'city' => 'KENITRA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MHMD', 'city' => 'mohammedia', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AINA', 'city' => 'AIN EL AOUDA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TMR', 'city' => 'TEMARA', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AIHR', 'city' => 'AIN HAROUDA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BSK', 'city' => 'Bouskoura', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'RHM', 'city' => 'Errahma', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MDN', 'city' => 'Mediouna', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'NOUC', 'city' => 'Nouacer', 'fee' => 40, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TMRS', 'city' => 'Tamaris', 'fee' => 40, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TTML', 'city' => 'Tit Melil', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'DR', 'city' => 'Deroua', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BRCH', 'city' => 'Berrechid', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'STT', 'city' => 'Settat', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HDS', 'city' => 'Had Soualem', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BZNK', 'city' => 'Bouznika', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BSLM', 'city' => 'Benslimane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'CHLALAT', 'city' => 'Chellalat Mohammedia', 'fee' => 40, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'MNSR', 'city' => 'El Mansouria', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'WSLN', 'city' => 'Ouislane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'NDR', 'city' => 'Nador', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AinAttig', 'city' => 'Ain Attig', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SALE', 'city' => 'SALE', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TIKIW', 'city' => 'Tikiwin', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'AITMLL', 'city' => 'AIt Melloul', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'INZG', 'city' => 'Inzegane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BNHD', 'city' => 'BEN AHMED', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HJB', 'city' => 'El Hajeb', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OLTYB', 'city' => 'Oulad Tayeb', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'MJTKNES', 'city' => 'Mejat - Région de Fès-Meknès', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Saiss', 'city' => 'Saiss', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Agourai', 'city' => 'Agourai', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TAZA', 'city' => 'Taza', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AZR', 'city' => 'AZROU', 'fee' => 45, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Ifran', 'city' => 'Ifran', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MZRH', 'city' => 'Moulay Idriss zerhouni', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BFK', 'city' => 'Boufakrane', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'GLMM', 'city' => 'Guelmim', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SDHRAZ', 'city' => 'Sidi Hrazem', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ZGHNZ', 'city' => 'Zeghanghane', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BNSR', 'city' => 'Beni Ensar', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BRK', 'city' => 'Berkane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SLO', 'city' => 'Selouane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'GRCF', 'city' => 'Guercif', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SAD', 'city' => 'Saidia', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MDGH', 'city' => 'Madagh', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Bouarg', 'city' => 'Bouarg', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Afra', 'city' => 'Afra', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Jaadar', 'city' => 'Jaadar', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'DRSAM', 'city' => 'Dar Essalam', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TSLT', 'city' => 'Tssoultante', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TMLL', 'city' => 'Tamellalt', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'CHMAA', 'city' => 'Echemmaia', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SFR', 'city' => 'SEFROU', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SLJAD', 'city' => 'Sala El Jadida', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Dkhl', 'city' => 'Dakhla', 'fee' => 50, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'thl', 'city' => 'TAHLA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MDR', 'city' => 'MIDAR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'rsn', 'city' => 'rissani', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Elatouia', 'city' => 'El attaouia', 'fee' => 40, 'delay' => '48h', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BARF', 'city' => 'BOUARFA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'Laay', 'city' => 'Laayoune', 'fee' => 50, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'klsrgh', 'city' => 'kelaa seraghna', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'ZGR', 'city' => 'ZAGORA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ERCHD', 'city' => 'ERRACHIDIA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'tnnt', 'city' => 'TANANT', 'fee' => 35, 'delay' => '48h', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'smara', 'city' => 'essemara', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'TNJD', 'city' => 'TINJDAD', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'khmst', 'city' => 'khemisset', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'MSR', 'city' => 'MISSOUR', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'RIBATLKH', 'city' => 'Ribate el kheir', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SATZ', 'city' => 'Sidi Allal Tazi', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'LAACHRQ', 'city' => 'El aioun Charqiya', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'ZAIDA', 'city' => 'ZAIDA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'IMOUZAR', 'city' => 'Imouzar marmoucha (Midelt)', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SIDIADDI', 'city' => 'Sidi Addi (AZROU)', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'tmhd', 'city' => 'Timhdit (azrou)', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'jorfsfr', 'city' => 'Jorf lasfar (eljadida)', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'anz', 'city' => 'Anza(agadir)', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'sbtgz', 'city' => 'Sebt El Guerdane(agadir)', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'skc', 'city' => 'sidi kacem', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'sidislm', 'city' => 'sidi sliman', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bngrir', 'city' => 'ben guerir', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'touarirt', 'city' => 'taourirt', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'trdnt', 'city' => 'taroudant', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'tntn', 'city' => 'tantan', 'fee' => 50, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'sidiifni', 'city' => 'sidi ifni', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'ALNF', 'city' => 'ALNIF', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TNGHR', 'city' => 'TINGHIR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'mdlt', 'city' => 'MIDLT', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'chchou', 'city' => 'chichaoua', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Tznt', 'city' => 'TIZNIT', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'Bennsar', 'city' => 'BENI NSAR ( NADOR )', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BOMIA', 'city' => 'BOUMIA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BENTAIB', 'city' => 'BEN TAIB', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'taou', 'city' => 'Taounate', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Fgg', 'city' => 'Figuig', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'GLLMIMA', 'city' => 'GOULMIMA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'zaio', 'city' => 'zaio', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'GARA', 'city' => 'EL GARA', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TATA', 'city' => 'TATA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BGIG', 'city' => 'BIOGRA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BLFAA', 'city' => 'BELFAA AGADIR', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SIDIBB', 'city' => 'SIDI BIBI', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TFRT', 'city' => 'TAFRAOUTE', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'HOUARA', 'city' => 'HOUARA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'AITAMR', 'city' => 'AIT AMIRA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'TAIMA', 'city' => 'OULAD TAIMA', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'BLMN', 'city' => 'BOULMANE', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MNZL', 'city' => 'El menzel-sefrou', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'imzkndr', 'city' => 'imouzar kandar-FES', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MCHRAKSIRI', 'city' => 'MECHRAA BELKSIRI', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 5],
        ['code' => 'SKLARB', 'city' => 'SOUK LARBAA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SIDIYAHYA', 'city' => 'SIDI YAHYA ELGHARB', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AZZ', 'city' => 'Azemmour', 'fee' => 40, 'delay' => '24H', 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SUIGD', 'city' => 'Souira Guedima', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'Bouguedra', 'city' => 'Tlat Bouguedra', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'HRH', 'city' => 'Harhoura', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'MHD', 'city' => 'Mehdia', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Skhirat', 'city' => 'Skhirat', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'Tamesna', 'city' => 'Tamesna', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Tiflet', 'city' => 'Tiflet', 'fee' => 45, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'dmnt', 'city' => 'Demnat', 'fee' => 30, 'delay' => null, 'refusal_fee' => 0, 'return_fee' => 0],
        ['code' => 'errich', 'city' => 'errich', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'erfd', 'city' => 'erfoud', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OUFS', 'city' => 'aoufous', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BDN', 'city' => 'boudnib', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TJD', 'city' => 'tinejdad', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TRG', 'city' => 'touroug', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MLB', 'city' => 'mellab', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'jrd', 'city' => 'JERADA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ESF', 'city' => 'essifa', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MRZGA', 'city' => 'MERZOGA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TRMGT', 'city' => 'Tarmigt', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'IDSN', 'city' => 'Idelsane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TNDT', 'city' => 'Toundoute', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KATMGN', 'city' => 'Kelaat M\'gouna', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SKHMDAD', 'city' => 'Souk Khemis Dades', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BNGR', 'city' => 'BEN GEURIR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SDBTHM', 'city' => 'SIDI BOUTHMAN', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TMELT', 'city' => 'TAMELET', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ATORIR', 'city' => 'AIT OURIR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ORK', 'city' => 'OURIKA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SIABGH', 'city' => 'SIDI ABDELAH GHYAT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'CHWTR', 'city' => 'CHWETER', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'LDY', 'city' => 'LOUDAYA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SZN', 'city' => 'SIDI ZOUIN', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'IMTNT', 'city' => 'IMINTANOUT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MEJT', 'city' => 'MEJJAT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AMZMZ', 'city' => 'AMIZMIZ', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'THNT', 'city' => 'TAHNAOUT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ASN', 'city' => 'ASNI', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OLDHSN', 'city' => 'OULAD HASOUN', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HDRSLAN', 'city' => 'HAD RASE LAIN', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'DRTNS', 'city' => 'DAR TONSI', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'NZT LADM', 'city' => 'NZALT LAADAM', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'STB SASI', 'city' => 'SABT BEN SASI', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SWHL', 'city' => 'SWIHLA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'IFKHR', 'city' => 'IFKHARA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'UGWDR', 'city' => 'IGWIDIR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TSLTNT', 'city' => 'TASLTANT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'DWRLHN', 'city' => 'DWAR LAHNA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'LHBICHT', 'city' => 'LAHBICHAT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'LAAGBTRK', 'city' => 'LAAGRAB TROURIKA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TMSLHT', 'city' => 'TAMSLOHT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'LATAKRST', 'city' => 'LALA TAKRKOST', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BMND', 'city' => 'Boumalne Dades', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'IMDR', 'city' => 'Imider', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TMDRN', 'city' => 'Timadrouine', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MSR', 'city' => 'Msemrir', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TLMI', 'city' => 'Tilmi', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ATSDRT', 'city' => 'Ait sedrat', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TZNKHT', 'city' => 'Taznakht', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AGDZ', 'city' => 'Agdez', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TNSKHT', 'city' => 'Tansikht', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TNZOLN', 'city' => 'Tinzouline', 'fee' => 40, 'delay' => null, 'refusal_fee' => 40, 'return_fee' => 0],
        ['code' => 'TMGRT', 'city' => 'Tamegroute', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TGNT', 'city' => 'Tagounite', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MHD GHZLN', 'city' => 'Mhamid El Ghizlane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TGBLT', 'city' => 'Taghbalt', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TZRN', 'city' => 'Tazarine', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'NKB', 'city' => 'Nkob', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TMDN', 'city' => 'Timdeline', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ATBNHD', 'city' => 'Ait Benhddou', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'IGHM NGD', 'city' => 'Ighrem N\'ougda', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AGIM', 'city' => 'Agouim', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AMRGN', 'city' => 'Amerzgane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MAghr', 'city' => 'MOULAY ABDELAH AMGHAR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HDOLDFRJ', 'city' => 'hed ouled fraj', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OLDGHNM', 'city' => 'OLD GHANAM', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AZEMR', 'city' => 'AZEMOUR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SDBNR', 'city' => 'SIDI BENNOUR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ZT SDSML', 'city' => 'ZAOUIAT SIDI SMAIL', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ZMMRA', 'city' => 'ZEMAMRA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AN ATG', 'city' => 'AIN ATIG', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SKHRT', 'city' => 'SEKHIRAT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MRSELKHIR', 'city' => 'MERS EL KHEIR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BST MNZH', 'city' => 'BASSATIN EL MENZH', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HAROURA', 'city' => 'HAROURA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ERRIBA', 'city' => 'ERRIBA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AINHLF', 'city' => 'AIN HALOUF', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SD BTCH', 'city' => 'SIDI BETACH', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ROMN', 'city' => 'ROMMANI', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SBTMRCHOCH', 'city' => 'SEBT EL MARCHOUCH', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HD LBRCHA', 'city' => 'HAD LABRACHOUA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HDLGHWLM', 'city' => 'HAD LAGHWALEM', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'JMAT ERACHD', 'city' => 'JEMAAT ERROUACHAD', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TNT', 'city' => 'TAN-TAN', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ELOTA', 'city' => 'EL OUATIA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ZRIL', 'city' => 'ZRIOUILA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BZKRN', 'city' => 'BOUIZAKARNE', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TTLN', 'city' => 'TOUTLINE', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TGNT', 'city' => 'TAGANTE', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TMLY', 'city' => 'TIMOULAY', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'IFRAN', 'city' => 'IFRANe ATLAS SAGHIR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TGMT', 'city' => 'TAGMOUT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'FASK', 'city' => 'FASK', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TRGMT', 'city' => 'TARGOUMAÏT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ANASS', 'city' => 'Ain Ariss', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KHNIST', 'city' => 'khenishat', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'DARBM3Z', 'city' => 'douar boum3iz', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'HD KORT', 'city' => 'HAD KORT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OLD DD', 'city' => 'Oulad Daoud', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ZOUIASD KCM', 'city' => 'Zaouia Sidi Kacem', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OLD BNHMD', 'city' => 'Ouled Ben Hammadi', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MSMD', 'city' => 'MASMOUDA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BND', 'city' => 'BENOUDA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'LBGR', 'city' => 'LBGARA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'DR GDD', 'city' => 'dar gueddari', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'DR LASLJI', 'city' => 'Dar Laaslouji', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'JMA HFT', 'city' => 'Jemaa Haouafate', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MCHR BLKSR', 'city' => 'MACHRA BELKSSIRI', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SFSF', 'city' => 'Sefsaf', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MLYBSLHM', 'city' => 'Moulay bouslham', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'LAL MINOUN', 'city' => 'lalla mimouna', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ALAL TAZI', 'city' => 'ALAL TaZI', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MNSR', 'city' => 'Mnasra', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SD TB', 'city' => 'Sidi taibi', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BONKNDL', 'city' => 'Boulknadel', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BHALIL', 'city' => 'BHALIL', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MHYA', 'city' => 'M\'haya', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AITTJD', 'city' => 'AIN Taoujdate', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AIT OALL', 'city' => 'AIT OUALLAL', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'OLDTYB', 'city' => 'ouled tayeb', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AIN LAAH', 'city' => 'AIN LAAH', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AIT SEBT', 'city' => 'ait sebaa', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BTT', 'city' => 'bittit', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'DYT AOUA', 'city' => 'dayet aoua', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'guIG', 'city' => 'guigou', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MLY YKB', 'city' => 'moulay yakoub', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ain aicha', 'city' => 'ain aicha', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TISS', 'city' => 'tissa', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BDL', 'city' => 'bouadel', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AN MDN', 'city' => 'ain mediouna', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ZRZR', 'city' => 'zrizer', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BOHD', 'city' => 'bouhouda', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KHLLF', 'city' => 'KHLALFA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KRTBMHM', 'city' => 'kariat ba mohamed', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'GHFSI', 'city' => 'GHAFSAI', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SKSBMIMN', 'city' => 'souk sebt oulad mimoun', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'GHALAZ', 'city' => 'GHALAZ', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SDALMKHF', 'city' => 'SID ALMAKHFI', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ourtzarh', 'city' => 'ourtzarh', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Ain chqef', 'city' => 'Ain chqef', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'Ain chegg', 'city' => 'Ain cheggag', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'MTMT', 'city' => 'matmata', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BZMLN', 'city' => 'bouzemlane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'SDYSFAHD SNHJ', 'city' => 'sidi youssef ben ahmed senhaja', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'mtarnargha', 'city' => 'mtarnargha', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bouarous', 'city' => 'bouarous', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bir tmtm', 'city' => 'bir tamtam', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'azzaba', 'city' => 'azzaba', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ain bumssay', 'city' => 'ain boumassay', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'RS TBD', 'city' => 'ras tbouda', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'RBTALKHIR', 'city' => 'ribat alkhir', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ALROUI', 'city' => 'al aroui', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bni nssar', 'city' => 'bni nssar', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'farkhana', 'city' => 'farkhana', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bni chikar', 'city' => 'bni chikar', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'aklim', 'city' => 'aklim', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KRIT ARKMN', 'city' => 'kariat arckmane', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'DRIOUCH', 'city' => 'DRIOUCH', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BEN TAEIB', 'city' => 'BEN TAEIB', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'dar el kebdani', 'city' => 'dar el kebdani', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TZTOTN', 'city' => 'TIZTOUTINE', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bouyafar', 'city' => 'bouyafar', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'tafersit', 'city' => 'tafersit', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BNSIDLLOT', 'city' => 'bni sidel louta', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'telat azlaf', 'city' => 'telat azlaf', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'KSITA', 'city' => 'kassita', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'ait kamra', 'city' => 'ait kamra', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bni abdellah', 'city' => 'bni abdellah', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bni hdifa', 'city' => 'bni hdifa', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'targuist', 'city' => 'targuist', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'tala youssef', 'city' => 'tala youssef', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bni boufrah', 'city' => 'bni boufrah', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'rwadi', 'city' => 'rwadi', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'izemouren', 'city' => 'izemouren', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'tizi tchen', 'city' => 'tizi tchen', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TLAT KTAMA', 'city' => 'TLAT KTAMA', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'issagen', 'city' => 'issagen', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'swani', 'city' => 'swani', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'boukidan', 'city' => 'boukidan', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'krona', 'city' => 'krona', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'bni bouyach', 'city' => 'bni bouyach', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'tamssaman', 'city' => 'tamssaman', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'boudinar', 'city' => 'boudinar', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'tazaghine', 'city' => 'tazaghine', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'zagzal', 'city' => 'zagzal', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'BNIDRAR', 'city' => 'BNIDRAR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'TAFOUGHALT', 'city' => 'TAFOUGHALT', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'AHFIR', 'city' => 'AHFIR', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
        ['code' => 'regagada', 'city' => 'regagada', 'fee' => 40, 'delay' => null, 'refusal_fee' => 10, 'return_fee' => 0],
    ],
];
